stages:
  - build
  - test
  - deploy

variables:
  FLUTTER_VERSION: "3.27.2" # Sesuaikan dengan versi yang kamu gunakan

before_script:
  - apt-get update && apt-get install -y unzip curl
  - curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_$FLUTTER_VERSION-stable.tar.xz
  - tar -xf flutter.tar.xz
  - export PATH="$PATH:$CI_PROJECT_DIR/flutter/bin"
  - flutter --version

build:
  stage: build
  script:
    - flutter pub get
    - flutter build apk --release

test:
  stage: test
  script:
    - flutter test

deploy:
  stage: deploy
  only:
    - main # Hanya berjalan di branch utama
  script:
    - echo "Deploying..."
    - cp build/app/outputs/flutter-apk/app-release.apk public/
