// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5pcA61Z7hIrzvE8UsDrIPwftyt0G2xQ',
    appId: '1:856172251883:web:65188e14ef0fbd1fb90cae',
    messagingSenderId: '856172251883',
    projectId: 'laporan-kerja-71c97',
    authDomain: 'laporan-kerja-71c97.firebaseapp.com',
    storageBucket: 'laporan-kerja-71c97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUSm4gkaxN3i9pbtTVA-jSzkkYGBs5OQ',
    appId: '1:856172251883:android:80e3f0b53d4e6d71b90cae',
    messagingSenderId: '856172251883',
    projectId: 'laporan-kerja-71c97',
    storageBucket: 'laporan-kerja-71c97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7xrwndFRey52kWXitqCZ535r7Ny_Li8',
    appId: '1:856172251883:ios:07d88bca4b378ae1b90cae',
    messagingSenderId: '856172251883',
    projectId: 'laporan-kerja-71c97',
    storageBucket: 'laporan-kerja-71c97.firebasestorage.app',
    iosBundleId: 'com.example.laporan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa7xrwndFRey52kWXitqCZ535r7Ny_Li8',
    appId: '1:856172251883:ios:07d88bca4b378ae1b90cae',
    messagingSenderId: '856172251883',
    projectId: 'laporan-kerja-71c97',
    storageBucket: 'laporan-kerja-71c97.firebasestorage.app',
    iosBundleId: 'com.example.laporan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI5pcA61Z7hIrzvE8UsDrIPwftyt0G2xQ',
    appId: '1:856172251883:web:109e0a85f0b2dfd6b90cae',
    messagingSenderId: '856172251883',
    projectId: 'laporan-kerja-71c97',
    authDomain: 'laporan-kerja-71c97.firebaseapp.com',
    storageBucket: 'laporan-kerja-71c97.firebasestorage.app',
  );
}
